### PR TITLE
CI - add more logs and separate artifacts per provider

### PR DESCRIPTION
**Pull request by eslutsky**

### CODE REVIEW

**Review by ahadas — APPROVED** [review]
that's a good step forward but what would really ease debugging issues and maybe accelerate execution time a bit is not to delete the namespace by default when the execution completes

**Comment by eslutsky** [comment]
> that's a good step forward but what would really ease debugging issues and maybe accelerate execution time a bit is not to delete the namespace by default when the execution completes



> that's a good step forward but what would really ease debugging issues and maybe accelerate execution time a bit is not to delete the namespace by default when the execution completes

for openstack-tests its  not using the ephemeral namespace, everything is `konveyor-forklift`  which is not deleted .

**Comment by ahadas** [comment]
@eslutsky ok, I didn't try openstack yet, I wrote the previous comment based on what I see for oVirt

**Comment by eslutsky** [comment]
@ahadas ,also added 2 CRs to the openstack artifacts: pvs and openstackvolumepopulator,
imo we can merge it

**Review by ahadas — APPROVED** [review]

**Pull request merged**
