### PR TITLE
Add cirros image to the  WORKSPACE

### PR DESCRIPTION
**Pull request by eslutsky**
This image is required for our CI virt-v2v stub container
https://github.com/kubev2v/forkliftci/pull/28

### CODE REVIEW

**Comment by eslutsky** [comment]
this image is required for our CI virt-v2v stub container
https://github.com/kubev2v/forkliftci/pull/28

**Review by ahadas — COMMENTED** [review]
lgtm but can you please also add the explanation (`This image is required for our CI virt-v2v stub container https://github.com/kubev2v/forkliftci/pull/28`) to the commit message so we'll see it easily with git blame?

**Review by mnecas — APPROVED** [review]
Please add some notes about the CI.

**Review by ahadas — APPROVED** [review]
we'll notice if anyone drops it because CI would fail and we can relatively easily trace why it was added now, so it looks good to me

**Pull request merged**
