### PR TITLE
chore(KONFLUX-4255): Onboard mtv-operator

### PR DESCRIPTION
**Pull request by ernesgonzalez33**
Taking the Dockerfile from downstream to build image in upstream (in the meantime just commenting the not needed things)

### CODE REVIEW

**Comment by ernesgonzalez33** [comment]
@mnecas PTAL

**Comment by ernesgonzalez33** [comment]
@yaacov @mnecas updated the Dockerfile here as well to make it work from `build/`

**Comment by ernesgonzalez33** [comment]
@mnecas @yaacov PTAL

**Review by yaacov — APPROVED** [review]
LGTM

**Review by mnecas — APPROVED** [review]
lgtm

**Pull request merged**
