### PR TITLE
Bazelify ova-provider

### PR DESCRIPTION
**Pull request by liranr23**
Build the ova provider server image using bazel.

### CODE REVIEW

**Comment by liranr23** [comment]
i can drop the bump of the 2 dependencies.

**Review by ahadas — APPROVED** [review]
I resolved the two issues that were reported by sonarcloud

**Comment by ahadas** [comment]
@liranr23 did you do sanity test of the ova provider?

**Comment by liranr23** [comment]
> @liranr23 did you do sanity test of the ova provider?

not yet. tried to figure first what to do with the sonarcloud.

**Comment by ahadas** [comment]
@liranr23 you can merge it after making a sanity check, @bkhizgiy works on an end-to-end test

**Pull request merged**
