### PR TITLE
MTV-446 | Warm: Add cbt check before migration

### PR DESCRIPTION
**Pull request by mnecas**
Issue:
Right now we have a check to fail the migration when we start to create the VM which does not have the CBT enabled. We should throw error much earlier before the customer even start the migration.

Fix:
Add a CBT check to the plan validation. This fix right now affects only VMware migrations.

### CODE REVIEW

**Comment by mnecas** [comment]
New error from UI:
image

**Comment by mnecas** [comment]
Error example from yaml plan:
```
  conditions:
    - category: Critical
      items:
        - ' id:vm-34 name:''mnecas-infra'' '
      lastTransitionTime: '2024-09-12T10:36:03Z'
      message: Changed Block Tracking (CBT) has not been enabled on some VM. This feature is a prerequisite for VM warm migration.
      reason: MissingGuestInformation
      status: 'True'
      type: VMMissingGuestIPs
```

**Comment by mnecas** [comment]
Once I toggle to turn off the warm migration:
image

**Review by yaacov — APPROVED** [review]
LGTM

**Pull request merged**
