### PR TITLE
Fix migrations from vSphere

### PR DESCRIPTION
**Pull request by ahadas**
The image of virt-v2v was missing the libguestfs-appliance and thus migrations from vSphere were broken since the switch to bazel. The smallest but more important part of this PR is to replace the base image of the forklift-virt-v2v container from ubi8-minimal to ubi8-minimal with the libguestfs-appliance.

Other than that, this PR includes minor refactoring (renaming files) related to getting the dependencies of virt-v2v and upgrade of the dependencies using the updated code.

### CODE REVIEW

**Review by liranr23 — APPROVED** [review]
I do wonder how did it work since we moved to bazel (did it work?).

**Comment by ahadas** [comment]
> (did it work?).

nope, it didn't - see above: "The image of virt-v2v was missing the libguestfs-appliance **and thus migrations from vSphere were broken since the switch to bazel**"

**Comment by ahadas** [comment]
@liranr23 ah you mean how did it work for you when testing the changes in forklift-controller? I think you used the 2.3.4 image of forklift-virt-v2v..

**Comment by liranr23** [comment]
> @liranr23 ah you mean how did it work for you when testing the changes in forklift-controller? I think you used the 2.3.4 image of forklift-virt-v2v..

yeah i think i did.

**Review by nyoxi — APPROVED** [review]

**Pull request merged**
