### PR TITLE
Fix vmMap race

### LINKED ISSUE #281: VMs that are successfully migrated from openstack are shown with Error
I created an openstack Plan with 4 VMs in for newly created NS. all four VMs are migrated and created successfully . I can start/stop them . However the UI screen represents green color for 3 steps migration and Errors at the same time.

ERROR

Discussed in slack with @bennyz - he thinks it is the issue is in the finalization 
If you would like to see the plan in mtv07: 'pa4-four-vms' in 'polina' NS (the target NS with created VMs - polina1)

### PR DESCRIPTION
**Pull request by bennyz**
r.vmMap may be stale if a previous VM has created it and the current VM didn't exist yet

Fixes #281

### CODE REVIEW

**Review by ahadas — COMMENTED** [review]
it looks good but why do we actually need to cache it?

**Comment by bennyz** [comment]
> it looks good but why do we actually need to cache it?

that is a good question, I didn't want to rattle the cage too much :)

**Comment by ahadas** [comment]
> > it looks good but why do we actually need to cache it?
> 
> that is a good question, I didn't want to rattle the cage too much :)

yeah but I just think that there's no end to that really - what if the vm exists in the cache but in an incorrect 'running' state?

**Review by ahadas — APPROVED** [review]
ok, so not getting the vm is significant because we return an error but if we get the vm in down state while it's up then the implication is that we trigger a call to update the vm - that's insignificant
it would be better though to post the VM with the desired 'Running' state instead now that we post the VM at the end of the migration process

**Pull request merged**
